version: '2'
services:
  demo:
    image: demo
    expose:
      - "8080"
    ports:
      - "8080:80"
    environment:
      STAGE: dev
      AWS_S3_REGION: ""
      AWS_S3_UPLOAD_BUCKET: ""
      APP_ID: ""
      APP_KEY: ""
      API_URL: "https://api.kairos.com"
      API_TIMEOUT: "10" 
      POLL_TIMEOUT: "300"
      DEMO1_ID: ""
      DEMO_SECRET_KEY: ""
      XDEBUG: "true"
      XDEBUG_CONFIG: "remote_host=10.254.254.254"
    volumes:
      - ./demo:/var/www/app/demo
